### PR TITLE
Fixes the Upload Media button bug and adds Debug links

### PR DESCRIPTION
**Pull request by raajtram**
The Upload Media button was inoperative because the minshare-meta-admin CSS file was called instead of the JS file.

Secondly, added debug links for Facebook and Twitter.

### CODE REVIEW

**Comment by raajtram** [comment]
@norcross do you think adding a link to the [Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool#) could be helpful here?

**Comment by norcross** [comment]
@raajtram I can't believe I overlooked the css / js file thing. I've got a commit I need to make anyway, so I'm gonna roll that up. can you open the debug link in a separate issue? I wanna discuss how to best implement it before we add it to a PR.

**Comment by norcross** [comment]
just fixed it in the latest commit

**Comment by norcross** [comment]
i'll take a look at this, but i don't think i'll be adding the tools to this, i want to keep it as lean as possible

**Pull request closed without merging**
